fix: allow installing keybroker-app again
Following ed6ce14140df ("refactor: improve dependency management."),
it's not possible to build/install keybroker-app on its own anymore:

  $ cargo install --root /tmp/install-path/ --path keybroker-app/
  ...
  error[E0433]: failed to resolve: could not find `Serialize` in `serde`
     --> keybroker-common/src/lib.rs:16:31
      |
  16  | #[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
      |                               ^^^^^^^^^ could not find `Serialize` in `serde`
      |
  note: found an item that was configured out
     --> .cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.210/src/lib.rs:342:37
      |
  342 | pub use serde_derive::{Deserialize, Serialize};
      |                                     ^^^^^^^^^
      = note: the item is gated behind the `serde_derive` feature

Specify the 'derive' serde feature to fix this.

Signed-off-by: Jean-Philippe Brucker <jean-philippe@linaro.org>